name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:


    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            # This is used to complete the identity challenge
            # with sigstore/fulcio when running outside of PRs.
            id-token: write

        steps:
        - 
            name: Checkout repository
            uses: actions/checkout@v3

        # Install the cosign tool except on PR
        # https://github.com/sigstore/cosign-installer
        - 
            name: Install cosign
            if: github.event_name != 'pull_request'
            uses: sigstore/cosign-installer@f3c664df7af409cb4873aa5068053ba9d61a57b6 #v2.6.0
            with:
                cosign-release: 'v1.11.0'
        - 
            name: Setup Docker buildx
            uses: docker/setup-buildx-action@v2
        
        -
            name: Log into registry ${{ env.REGISTRY }}
            if: github.event_name != 'pull_request'
            uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
            with:
              registry: ${{ env.REGISTRY }}
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_TOKEN }}
        
        -
            name: Extract Docker metadata
            id: meta
            uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
            with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        
        - 
            name: Build and push Docker image
            id: build-and-push
            uses: docker/build-push-action@v4
            with:
                push: ${{ github.event_name != 'pull_request' }} # Don't push on PR
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                cache-from: type=gha
                cache-to: type=gha,mode=max

        -
            name: Sign the image with cosign
            if: github.event_name != 'pull_request'
            run: cosign sign --key cosign.key ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tags }}